### ISSUE TITLE
Dependency cannot be resolved

### ISSUE THREAD

**Issue by guness** [WalletConnect-Labs/WalletConnectKotlinV2#109]
I am trying to include this dependency to the project. However current documented version string is not resolved.

However this works:
```implementation("com.github.WalletConnect-Labs:WalletConnectKotlinV2:1.0.0-test04")```

**Comment by TalhaAli00** [comment]
This has been addressed in https://github.com/WalletConnect/WalletConnectKotlinV2/issues/2
