### ISSUE TITLE
Find out how to store keys

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect-Labs/WalletConnectKotlinV2#20]
Currently, the WC SDK is a JVM library. To store keys and still keep the library a JVM library, we have several options. 
* We can have the client app pass in the app's directory for the internal storage and then use our own storage library and create either a Key-Value file or a DB file at the storage site. We will have to put in the documentation which functions the client will have to pass. This options gives us control of how we want to store the data but then we are also responsible for the security of the data being stored.
* We could also have the client app implement an interface and just pass the implementation to the SDK. With this option, the client has control of where and how the data is stored. This will also take the security responsibility away from the SDK. One downside to this option is that it could be error prone since we are expecting the client to properly set and receive the data we want.

If we are to convert the library to a Android library instead, we will have access to Android apis such as Secure SharedPreferences which is an encrypted KV framework. This option will give us control on how to set and get the data, rely on the Android framework to handle securing the data, as well as store into an internal directory so it will be harder to find the file we use to read and write our data.

**Comment by chadyj** [comment]
From our meeting:  Use memory based storage for now, and introduce improved storage as the beta progresses.

**Comment by tordjon** [comment]
Please don't convert this to an android library, that would prevent it being used by kotlin projects that are not built only for android, for example compose for desktop or compose for web applications, or as a common implementation for a KMM project.

Perhaps `https://developer.android.com/jetpack/androidx/releases/datastore` core (without any android dependencies) could be used instead of sharepreferences?

**Comment by TalhaAli00** [comment]
@tordjon We understand the desire to have a KMM compatible library and one day hope to be able to provide WalletConnect using KMP. But at the moment, ~95% of our users are on Android so we want to make sure we get Android down first before trying to generalize for other platforms.

**Comment by chaak** [comment]
Since, we made the decision in which direction we're currently facing I'm closing this issue.
