### ISSUE TITLE
Investigate Dependency Injection

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect-Labs/WalletConnectKotlinV2#24]
Look into a dependency injection framework to help manage dependencies through out the app. Prefer a compile time injection frameworks that support JSR-333 over service locator frameworks. Do some benchmark tests for each framework such as build times and size of compiled SDK. Use Dagger 2 as the control

Options:
* https://github.com/google/guice or https://github.com/misfitlabsdev/kotlin-guice
* https://github.com/evant/kotlin-inject
* https://github.com/corbella83/PopKorn
* https://docs.kodein.org/kodein-framework/index.html
* https://github.com/stephanenicolas/toothpick

**Comment by ligi** [comment]
I think dagger should be used if you want a compile time one - then also works together with hilt on android (https://developer.android.com/training/dependency-injection/hilt-android#hilt-and-dagger)
I personally mainly use Koin currently and am very happy with it - but if you want a compile time one - dagger should be the one IMHO

**Comment by TalhaAli00** [comment]
Dagger is a possibility but I want to see if there's a size difference for the SDK between the other options and Dagger. And the SDK will not leak the dependency framework, these frameworks will be internal only and not interact with the consumer's DI framework. The public face apis will be wrapped in a singleton class instead of an object that needs to be created and injected.

**Comment by mobilekosmos** [comment]
I recommend using Google's solution, Hilt, they know what it's better for/on Android.

**Comment by ligi** [comment]
@TalhaAli00 the size difference can easily fool you - let's say you measure one of the solutions you mentioned is smaller than dagger - but if the app already contains dagger (and it is way more common than the solutions you mentioned and as @mobilekosmos also recommended by the android team) then you save a lot of space just having one DI as dependency and not 2.

**Comment by TalhaAli00** [comment]
The sharing of a dependency is a good point so I'll def take that into consideration. The only time I see that not being the case is if a project is either using another DI framework like Koin or they are using a different version of Dagger. Then the client app will have the added size of Dagger that comes with the SDK.
As far as Hilt is concerned, the biggest issue is that it's an Android dependency that wouldn't work since the SDK is a Java library. But there's also the issue of not having interoperability between Hilt and Dagger 2 with how Hilt structures it's components. 
I'm going to using this issue as an investigatory task to see what the other options provide and if there's a significant size difference. My intention was to fallback to Dagger if any of the options either were too complicated or there was no significant benefit to using an alternative. I'll update the issue to better reflect the true intention and approach
