### ISSUE TITLE
Github proyect name

### ISSUE THREAD

**Issue by mobilekosmos** [WalletConnect-Labs/WalletConnectKotlinV2#39]
Just checking if you really want to use camelCase for naming the new proyects, since most of the others are lower case + dashes. I myself don't know [what's better](https://stackoverflow.com/questions/11947587/is-there-a-naming-convention-for-git-repositories).

**Comment by TalhaAli00** [comment]
Are you talking about the WalletConnectV2 module?

**Comment by mobilekosmos** [comment]
I'm talking about hte github proyect 
**WalletConnect-Labs/WalletConnectKotlinV2**

**Comment by TalhaAli00** [comment]
I think it's fine at the moment. The Kotlin and Swift libraries are both doing the same thing. We can look into changing the repo to lowercase in the future to be in sync with the JS repo. But thanks for bringing it up
