### ISSUE TITLE
What about chainID and supportedWallets params?

### ISSUE THREAD

**Issue by mobilekosmos** [WalletConnect-Labs/WalletConnectKotlinV2#81]
In v1 Kotlin passing the chainID and the list of supported Wallets Apps was not supported, will these be supported in v2? I couldn't find anything related in the Develop branch yet.

**Comment by chadyj** [comment]
There is some mentions in the docs:

https://docs.walletconnect.com/migration#multi-chain-support
https://docs.walletconnect.com/protocol/ux-considerations#chain-targetting

Does that help answer your question?

**Comment by mobilekosmos** [comment]
It helps, thanks, but what about the list of supported wallets? I think that is also part of the walletconnect spec somewhere. If not clear I mean the one param that you can define so that on mobile you only get a filtered list of wallets and not ALL wallets that support the handling of the passed uri.

**Comment by TalhaAli00** [comment]
I believe this falls outside of the responsibility of the WalletConnect SDK. I believe you are talking about the experience of connecting a wallet and a dapp which is the job of the developers for 3rd party wallets and dapps. The WalletConnect SDK is solely responsible for the communication between Web3 project, we have no say in the UI/UX of those projects. If there are other concerns, please create a new issue on our new repo: https://github.com/WalletConnect/WalletConnectKotlinV2
