### ISSUE TITLE
Expose public proposer methods to app

### ISSUE THREAD

**Issue by jakobuid** [WalletConnect-Labs/WalletConnectKotlinV2#86]
WalletConnectClient should expose public methods to app:

- [ ] initialize() - for both to initialize client wit network connection and client's meta data
- [ ] disconnect() - for either to disconnect a session
- [ ] request() - for proposer to request JSON-RPC
- [ ] getActivePairings() - for proposer to propose new sessions over active pairings
- [ ] upgrade() - for responder to upgrade session permissions
- [ ] update() - for responder to update session state
- [ ] notify() - for either to send notifications
- [ ] ping() - for both to ping and verify peer is online

**Comment by chaak** [comment]
Issues should be crated based on missing methods for proposer.
