### ISSUE TITLE
Suggestion: please consider bumping minSDK

### ISSUE THREAD

**Issue by mobilekosmos** [WalletConnect-Labs/WalletConnectKotlinV2#93]
Personally I wouldn't suggest to support Android OS versions which don't get any security updates anymore. WalletConnect is a key tech used in transacting value, security should be a top priority, so why should the lib support Android Versions which are not even supported by Google anymore?

**Comment by chaak** [comment]
Thanks for the suggestion. We consider to bump minSdk to 23 level.

**Comment by TalhaAli00** [comment]
Min version has been updated to API 23
